spring:
  application:
    name: poc-rabbitmq
  rabbitmq:
    port: 5672
    host: localhost
    username: admin
    password: test

management:
  endpoints:
    web:
      exposure:
        includ: "*"
